#cloud-config
runcmd:
  - [ sh, -c, "sleep 3m" ]
  - sudo apt update -y
  - sudo apt-get update
  - sudo apt-get -y upgrade
  - sudo apt install python3
  - sudo apt install git
  - git clone https://github.com/iampsrv/flask-app-aws.git
  - cd flask-app-aws
  - sudo apt-get -y install python3-pip
  - pip install -r req.txt
  - python3 main.py
  - sudo apt-get update
  - apt install -y apt-transport-https ca-certificates curl software-properties-common
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
  - apt update -y
  - apt-cache policy docker-ce
  - apt install -y docker-ce
  - mkdir /etc/docker
  - systemctl enable --now docker
  - usermod -aG docker ubuntu
  - systemctl restart docker

  - echo "Disabling SWAP"
  - swapoff -a
  - sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
  - sysctl net.bridge.bridge-nf-call-iptables=1
